#!/usr/bin/env bash
# Hybrid profile summary (OQ2): pdftotext draft → learner reviews profile-summary.md
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LFCS_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
PROFILE_DIR="${LFCS_ROOT}/ara_tutor/user-profile"
OUT="${PROFILE_DIR}/profile-summary.md"
DRAFT="${PROFILE_DIR}/.profile-draft.md"

log()  { printf '\033[1;34m[%s]\033[0m %s\n' "$(date '+%H:%M:%S')" "$*"; }
ok()   { printf '\033[1;32m  ✓ %s\033[0m\n' "$*"; }
die()  { printf '\033[1;31m  ✗ %s\033[0m\n' "$*" >&2; exit 1; }

command -v pdftotext >/dev/null 2>&1 || die "Install poppler-utils: sudo apt install poppler-utils"

[[ -d "${PROFILE_DIR}" ]] || die "Missing ${PROFILE_DIR}"

needs_update() {
  [[ ! -f "${OUT}" ]] && return 0
  local newest_pdf
  newest_pdf="$(find "${PROFILE_DIR}" -maxdepth 1 -name '*.pdf' -o -name '*.PDF' -printf '%T@\n' 2>/dev/null | sort -n | tail -1)"
  [[ -z "${newest_pdf}" ]] && return 1
  local out_mtime
  out_mtime="$(stat -c %Y "${OUT}" 2>/dev/null || echo 0)"
  awk "BEGIN { exit !(${newest_pdf} > ${out_mtime}) }"
}

if ! needs_update; then
  ok "profile-summary.md is up to date"
  exit 0
fi

log "Extracting PDF text to draft..."
{
  echo "# Learner profile summary (DRAFT — review before RAG indexing)"
  echo ""
  echo "> Generated by lfcs-profile-summarize.sh. Edit this file, then remove DRAFT banner."
  echo "> PDFs are excluded from RAG; only this summary is indexed."
  echo ""
  for pdf in "${PROFILE_DIR}"/*.pdf "${PROFILE_DIR}"/*.PDF; do
    [[ -f "${pdf}" ]] || continue
    base="$(basename "${pdf%.*}")"
    echo "## ${base}"
    echo ""
    pdftotext -layout "${pdf}" - 2>/dev/null | head -120 | sed 's/^/    /'
    echo ""
  done
  echo "## Learning preferences (edit manually)"
  echo ""
  echo "- Preferred explanation style: (concise / detailed / examples-first)"
  echo "- Best study time: "
  echo "- Weak LFCS areas: grep/awk/sed, docker-compose, git"
} > "${DRAFT}"

if [[ -f "${OUT}" ]]; then
  log "Existing summary preserved — draft at ${DRAFT}"
  ok "Review ${DRAFT} and merge into ${OUT}"
else
  cp "${DRAFT}" "${OUT}"
  ok "Created ${OUT} — please review and edit before RAG sync"
fi